language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# ./gradlew 권한 변경
before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 푸시되었을 때 수행하는 명렁어, clean & build
script: "./gradlew clean build"

# deploy 전에 실행
before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/springboot-project-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis에 설정해줬음
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-project-s3build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근 private
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis에 설정해줬음
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-project-s3build
    key: springboot-project-webservice.zip
    bundle_type: zip
    application: springboot-project-webservice
    deployment_group: springboot-project-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - cksal4278@gmail.com